### ISSUE TITLE
Error after "npm run-script build"

### ISSUE THREAD

**Issue by Arpanx** [Jin-K/simple-crm#1]
PS F:\WORK\simple-crm\SimpleCRM.App> npm run-script start

> simple-crm@0.0.0 start F:\WORK\simple-crm\SimpleCRM.App
> ng serve --host simple-crm

getaddrinfo ENOTFOUND simple-crm
Error: getaddrinfo ENOTFOUND simple-crm
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

**Comment by Jin-K** [comment]
Hi,
this repository is in development and I'm working alone on it, I didn't though that someone would test it.
I updated Readme.md and it should explain how to run it (I hope).
